### ISSUE TITLE
Wide-band cubes: allow for multiple beams along the spectral axis.

### ISSUE THREAD

**Issue by e-koch** [radio-astro-tools/spectral-cube#282]
I'm not sure if FITS header standards allow for defining multiple beams, but CASA images do define a beam per channel (MIRIAD too I think?). 

@low-sky brought this up.

**Comment by e-koch** [comment]
Some minor changes would also be needed in `radio_beam`.

**Comment by keflavich** [comment]
FITS headers don't support multiple beams, but CASA FITS files do by storing the beams in a bintablehdu

**Comment by keflavich** [comment]
This is becoming higher priority.  We also want a `smooth_to_common_beam` method, or something similar.  However, I'm worried about cluttering the namespace with radio-specific things; even though this is in radio-astro-tools, we have (and want) users at other wavelengths.  It may be good to subclass `SpectralCube` into `RadioSpectralCube` or `ALMASpectralCube`/`EVLASpectralCube`/`CASASpectralCube` in order to add beam-specific details.

**Comment by keflavich** [comment]
Solved by https://github.com/radio-astro-tools/spectral-cube/pull/437, https://github.com/radio-astro-tools/spectral-cube/pull/292.... wow this is ancient.
