### ISSUE TITLE
Reading cubes with improper CTYPE3 axis

### ISSUE THREAD

**Issue by ivvv** [radio-astro-tools/spectral-cube#324]
I have spectral cubes from the Herschel Space Observatory and unfortunately the CTYPE3 FITS header keyword contains a bogus '&' symbol in the name. So, it's 'Frequency&' instead of 'Frequency'.

I tried to use the meta parameter in the SpectralCube.read(), like this:

`xx = SpectralCube.read(file,hdu=1,meta={'CTYPE3': 'FREQ'})
`
but this does not seem to work. Actually, the documentation on the meta input parameter is inexistent and I was just shooting in the dark with this experiment, as I am not quite sure if this will only change this metadatum. Well, I can look at the code...

The workaround I found was to read the cube, change the CTYPE3 and then create the SpectralCube object:

```
xx = fits.open(file)
cube = xx['image'].data
header = xx['image'].header
header["CTYPE3"] = "FREQ"
yy = SpectralCube(data=cube,wcs=WCS(header))
yy[10,:,:].quicklook()
```

This works but it's a bit ugly. So, maybe for such non-standard headers the user could still have some control on setting some keywords to their standard names. I expected the meta parameter to be used for this.

I can provide an example spectral cube from the Herschel SPIRE Fourier-Transform Spectrometer. 
Thanks,
Ivan

**Comment by keflavich** [comment]
It would be great if you could provide a link to some SPIRE cubes, or failing that, just copy & paste an example header here.  We can try to find a workaround for this, but honestly your 'ugly' approach is (almost) exactly what I would do.  This issue should probably be reported to the Herschel archive too.

**Comment by keflavich** [comment]
@ivvv ok, thanks. Is there an API for the Herschel archive?  Perhaps we could hook up an astroquery frontend to it and correct the headers upon download.  This is mostly unrelated to your issue, which we can try to work around directly within spectral-cube, but it would still possibly be a useful service to the community.

**Comment by ivvv** [comment]
Yes, [http://archives.esac.esa.int/hsa/aio/doc/howto.html](this is the API for the Herschel Science Archive). Good luck with it :-)

Maybe we should continue the astroquery topic outside this thread. Please can you get in contact on my gmail email ivvv68 ?

**Comment by ivvv** [comment]
According to the developer, the FITS files are following the OGIP standard and fits verify() does not indicate any issue with the headers. Is it possible that the wcslib does not properly parse keywords with '&' symbols?

**Comment by keflavich** [comment]
Huh, well, if it is valid FITS, wcslib should be handling it... maybe we should take this upstream to astropy?

**Comment by e-koch** [comment]
Yes. WCS isn't recognizing it as a spectral axis:
```
test_open = fits.open("hspirespectrometer1342204895_spg_SSW_convol_HR_20ssc_1461253633867.fits.gz")
mywcs = wcs.WCS(test_open[2])
mywcs.get_axis_types()[2]
```
gives
```
{u'coordinate_type': None, u'group': 0, u'number': 0, u'scale': u'linear'}
```

**Comment by astrofrog** [comment]
So the issue is that WCSLIB (which we use in Astropy) does not handle the CONTINUE convention in WCS keywords (which is used for CTYPE3). Mark Calabretta says:

*CONTINUE is only a convention, not a standard.  The fact that the
convention is "registered" effectively only means that the keyword is
reserved, not that it must be supported.  Using it for standard keywords
is ill-advised to say the least.*

*Actually, the WCSLIB function, fitshdr(), does support a generalisation
of the CONTINUE convention but only when parsing a generic header.  It
should never be needed for any of the WCS keywords, and indeed, its use
in the offending header is purely gratuitous.  In fact, every use of
CONTINUE in that FITS file is unnecessary!*

*I suggest editing the header with emacs or vim in binary mode and
removing the ampersand.  Whoever wrote the header should be advised not
to use CONTINUE for any of the standard FITS keywords.*

If we do want to support this in spectral-cube then I think what we need to do is pre-parse and fix the header before passing it on to astropy.wcs.
