### ISSUE TITLE
CASA stuff in spectral-cube

### ISSUE THREAD

**Issue by pllim** [radio-astro-tools/spectral-cube#340]
In the [Masking](http://spectral-cube.readthedocs.io/en/latest/masking.html#outputting-masks) section, it was mentioned that certain API is CASA-specific and will not run outside "CASA python session". As a non-CASA user, it seems to me that the CASA-specific stuff should be taken out of `spectral-cube` and put in some CASA-specific package. Just a thought.

**Comment by keflavich** [comment]
I'm opposed to splitting out any more functionality than we already have because it is an extra barrier to adoption.  Also, there is some political motivation to keep in CASA-specific tasks: some of the funding to support this project came from ALMA via NRAO/ESO.

On the other hand, longer-term, it might make sense to split out `SpectralCube` into a fully generic version to incorporate into astropy-core and a radio-specific wrapper to keep here and possibly tied to CASA.  That's a lot of work, though, enough so that it may never happen.

**Comment by pllim** [comment]
Thanks for the clarifications. While I understand the political ramifications, perhaps we should just keep this issue open as a "wish list" reminder.

**Comment by astrofrog** [comment]
I'm going to close this because with CASA 6, it's now possible to install CASA into a user's environment with pip, so there's less of a distinction between CASA and non-CASA things in spectral-cube.
