### ISSUE TITLE
Provide a way to temporarily store the data array in ``DaskSpectralCube`` to a zarr array

### ISSUE THREAD

**Issue by astrofrog** [radio-astro-tools/spectral-cube#627]
We should provide a way in ``DaskSpectralCube`` to dump the current dask array to disk in a zarr array and then re-loading it straight away, as a way to effectively force a computation and avoid long chains of e.g. spectral then image then spectral operations which could be quite inefficient. This would be the equivalent of the ``use_memmap`` option in some methods in the plain ``SpectalCube``. Note however that this would just be a generic method rather than adding an option to all methods (alternatively it could be added to all methods via a decorator, but I think a separate explicit method would be nicer). Any suggestions for API?

**Comment by keflavich** [comment]
Can we have a subclass, or a boolean property like `allow_huge=True/False` that does all operations through `zarr`-dumps when set?  So if you're using a really big cube, all operations happen through the non-memory path?

Otherwise, the optional argument to each operation sounds nice as an API, though a pain to implement.
